# This file is managed centrally by modulesync
#   https://github.com/maestrodev/puppet-modulesync

source 'https://rubygems.org'

gem 'puppet', ENV['PUPPET_VERSION'] || '<%= @configs['puppet_version'] -%>', :require => false

<% (@configs['required'] + (@configs['extra'] || [])).each do |gem| -%>
gem '<%= gem['gem'] %>'<%= ", '#{gem['version']}'" if gem['version'] %>, :require => false
<% end -%>

# vim:ft=ruby
