# This file is managed centrally by modulesync
#   https://github.com/maestrodev/puppet-modulesync

source 'https://rubygems.org'

gem 'puppet', ENV.key?('PUPPET_VERSION') ? "~> #{ENV['PUPPET_VERSION']}" : '>= 2.7'

<% (@configs['required'] + (@configs['extra'] || [])).each do |gem| -%>
gem '<%= gem['gem'] %>'<%= ", '#{gem['version']}'" if gem['version'] %>, :require => false
<% end -%>

# vim:ft=ruby
